AWSTemplateFormatVersion: "2010-09-09"
Description: "Prefix-based IAM Role and Managed Policy for Atlantis Service Role to be assumed when deploying full network stacks (CloudFront + Route53) - Deployed using SAM"

# Atlantis for AWS SAM Deployments
# Service Role Infrastructure Template
# Author: Chad Kluck - 63klabs.net
# Version: v0.0.0/2026-04-23

# Documentation, Issues/Feature Requests, Latest Updates, and Security Reports on GitHub:
# https://github.com/63klabs/atlantis-cfn-template-repo-for-serverless-deployments/

# USE WITH:
# - Network: template-network-route53-cloudfront-s3-apigw.yml
#   - templates/v2/network/template-network-route53-cloudfront-s3-apigw.yml

# =============================================================================
# META DATA
# -----------------------------------------------------------------------------
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-interface.html
#

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Application Resource Naming"
        Parameters:
          - Prefix
          - PrefixUpper
          - S3BucketNameOrgPrefix
          - ServiceRolePath
      -
        Label:
          default: "External Resources"
        Parameters:
          - PermissionsBoundaryArn
      -
        Label:
          default: "Resources to Attach Managed Policy To"
        Parameters:
          - GroupNames
          - UserNames
          - RoleNames
      -
        Label:
          default: "Module Locations"
        Parameters:
          - NetworkCloudFrontMgmtPolicyModuleUrl
          - NetworkRoute53MgmtPolicyModuleUrl
          - NetworkFullMgmtRoleModuleUrl

# =============================================================================
# PARAMETERS
# -----------------------------------------------------------------------------

Parameters:

  Prefix:
    Type: String
    Default: "acme"
    AllowedPattern: "^[a-z][a-z0-9-]{0,6}[a-z0-9]$"
    MinLength: 2
    MaxLength: 8

  PrefixUpper:
    Type: String
    Default: "ACME"
    AllowedPattern: "^[A-Z][A-Z0-9-]{0,6}[A-Z0-9]$"
    MinLength: 2
    MaxLength: 8

  S3BucketNameOrgPrefix:
    Type: String
    Default: ""
    AllowedPattern: "^[a-z0-9][a-z0-9-]{0,18}[a-z0-9]$|^$"

  ServiceRolePath:
    Type: String
    Default: "/"
    AllowedPattern: "^\\/([a-zA-Z0-9-_]+[\\/])+$|^\\/$"

  PermissionsBoundaryArn:
    Type: String
    Default: ""
    AllowedPattern: "^$|^arn:aws:iam::\\d{12}:policy\\/[\\w+=,.@\\-\\/]*[\\w+=,.@\\-]+$"

  GroupNames:
    Type: CommaDelimitedList
    Default: ""
    AllowedPattern: "^[\\w+=,_.@\\-]+$|^$"
  RoleNames:
    Type: CommaDelimitedList
    Default: ""
    AllowedPattern: "^[\\w+=,_.@\\-]+$|^$"
  UserNames:
    Type: CommaDelimitedList
    Default: ""
    AllowedPattern: "^[\\w+=,_.@\\-]+$|^$"

  NetworkCloudFrontMgmtPolicyModuleUrl:
    Type: String
    Description: "S3 URL of the network CloudFront management policy module."
    AllowedPattern: "^s3:\\/\\/[a-zA-Z0-9][a-zA-Z0-9\\-]{1,61}[a-zA-Z0-9]\\/.*\\.yml$"

  NetworkRoute53MgmtPolicyModuleUrl:
    Type: String
    Description: "S3 URL of the network Route53 management policy module."
    AllowedPattern: "^s3:\\/\\/[a-zA-Z0-9][a-zA-Z0-9\\-]{1,61}[a-zA-Z0-9]\\/.*\\.yml$"

  NetworkFullMgmtRoleModuleUrl:
    Type: String
    Description: "S3 URL of the full network management role module."
    AllowedPattern: "^s3:\\/\\/[a-zA-Z0-9][a-zA-Z0-9\\-]{1,61}[a-zA-Z0-9]\\/.*\\.yml$"

# =============================================================================
# CONDITIONS
# -----------------------------------------------------------------------------

Conditions:
  UseS3BucketNameOrgPrefix: !Not [!Equals [!Ref S3BucketNameOrgPrefix, ""]]
  HasPermissionsBoundaryArn: !Not [!Equals [!Ref PermissionsBoundaryArn, ""]]
  HasGroupNames: !Not [!Equals [!Join ["", !Ref GroupNames], ""]]
  HasRoleNames: !Not [!Equals [!Join ["", !Ref RoleNames], ""]]
  HasUserNames: !Not [!Equals [!Join ["", !Ref UserNames], ""]]

# =============================================================================
# RESOURCES
# -----------------------------------------------------------------------------

Resources:

  # ---------------------------------------------------------------------------
  # -- Network CloudFront Management Policy --
  # Module: modules/management-roles/network-cloudfront-mgmt-policy.yml

  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: !Ref NetworkCloudFrontMgmtPolicyModuleUrl

  # ---------------------------------------------------------------------------
  # -- Network Route53 Management Policy --
  # Module: modules/management-roles/network-route53-mgmt-policy.yml

  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: !Ref NetworkRoute53MgmtPolicyModuleUrl

  # ---------------------------------------------------------------------------
  # -- Full Network Management Role and PassRole Policy --
  # Module: modules/management-roles/network-full-mgmt-role.yml

  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: !Ref NetworkFullMgmtRoleModuleUrl

# =============================================================================
# OUTPUTS
# -----------------------------------------------------------------------------

Outputs:

  NetworkFullMgmtServiceRoleArn:
    Description: "The ARN of the Full Network Management Service Role (CloudFront + Route53)"
    Value: !GetAtt PrefixBasedCloudFormationNetworkFullMgmtServiceRole.Arn
    Export:
      Name: !Sub "${PrefixUpper}-CloudFormation-Network-Full-Mgmt-Service-Role-Arn"

  NetworkFullMgmtServiceRoleName:
    Description: "The Name of the Full Network Management Service Role"
    Value: !Ref PrefixBasedCloudFormationNetworkFullMgmtServiceRole
    Export:
      Name: !Sub "${PrefixUpper}-CloudFormation-Network-Full-Mgmt-Service-Role-Name"

  NetworkFullMgmtManagedPolicyArn:
    Description: "The ARN of the Full Network Management Managed Policy"
    Value: !Ref PrefixBasedNetworkFullMgmtManagedPolicy
    Export:
      Name: !Sub "${PrefixUpper}-CloudFormation-Network-Full-Mgmt-ManagedPolicy-Arn"
